#######################################################################
# S3 REMOTE STATE
#######################################################################
bucket = "dev-hospital-pms-tfstate"
key    = "dev/terraform.tfstate"
region = "us-east-1"
# dynamodb_table = "hospital-pms-tf-locks"
encrypt = true
