#######################################################################
# S3 REMOTE STATE
#######################################################################
bucket = "qa-hospital-pms-tfstate"
key    = "qa/terraform.tfstate"
region = "us-east-1"
# dynamodb_table = "hospital-pms-tf-locks"
encrypt = true
